///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GradeModelGradesExam {
/*
{
  "id": 1,
  "name": "امتاحان شهر اول"
}
*/

  int? id;
  String? name;

  GradeModelGradesExam({
    this.id,
    this.name,
  });
  GradeModelGradesExam.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class GradeModelGradesSubject {
/*
{
  "id": 2,
  "name": "OOP Java"
}
*/

  int? id;
  String? name;

  GradeModelGradesSubject({
    this.id,
    this.name,
  });
  GradeModelGradesSubject.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class GradeModelGrades {
/*
{
  "id": 1,
  "grade": 100,
  "exam_id": 1,
  "student_id": 1,
  "subject_id": 2,
  "created_at": "2021-12-04T00:24:04.000000Z",
  "updated_at": null,
  "subject": {
    "id": 2,
    "name": "OOP Java"
  },
  "exam": {
    "id": 1,
    "name": "امتاحان شهر اول"
  }
}
*/

  int? id;
  int? grade;
  int? examId;
  int? studentId;
  int? subjectId;
  String? createdAt;
  String? updatedAt;
  GradeModelGradesSubject? subject;
  GradeModelGradesExam? exam;

  GradeModelGrades({
    this.id,
    this.grade,
    this.examId,
    this.studentId,
    this.subjectId,
    this.createdAt,
    this.updatedAt,
    this.subject,
    this.exam,
  });
  GradeModelGrades.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    grade = json['grade']?.toInt();
    examId = json['exam_id']?.toInt();
    studentId = json['student_id']?.toInt();
    subjectId = json['subject_id']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    subject = (json['subject'] != null) ? GradeModelGradesSubject.fromJson(json['subject']) : null;
    exam = (json['exam'] != null) ? GradeModelGradesExam.fromJson(json['exam']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['grade'] = grade;
    data['exam_id'] = examId;
    data['student_id'] = studentId;
    data['subject_id'] = subjectId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (subject != null) {
      data['subject'] = subject!.toJson();
    }
    if (exam != null) {
      data['exam'] = exam!.toJson();
    }
    return data;
  }
}

class GradeModel {
/*
{
  "id": 1,
  "grades": [
    {
      "id": 1,
      "grade": 100,
      "exam_id": 1,
      "student_id": 1,
      "subject_id": 2,
      "created_at": "2021-12-04T00:24:04.000000Z",
      "updated_at": null,
      "subject": {
        "id": 2,
        "name": "OOP Java"
      },
      "exam": {
        "id": 1,
        "name": "امتاحان شهر اول"
      }
    }
  ]
}
*/

  int? id;
  List<GradeModelGrades?>? grades;

  GradeModel({
    this.id,
    this.grades,
  });
  GradeModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    if (json['grades'] != null) {
      final v = json['grades'];
      final arr0 = <GradeModelGrades>[];
      v.forEach((v) {
        arr0.add(GradeModelGrades.fromJson(v));
      });
      grades = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (grades != null) {
      final v = grades;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['grades'] = arr0;
    }
    return data;
  }
}
